config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"
  
  get "about", to: "about#index"
  get "contact", to: "about#contact"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  validates :commenter, presence: true
  validates :body, presence: true
  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  class_methods do
    def public_count
      where.not(commenter: nil).count
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def contact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  http_basic_authenticate_with name: 'cobalt', password: 'cobalt', except: [:index, :show]
  
  def index
    @articles = Article.all
    @articles = @articles.reverse
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
  private

    def article_params
      params.require(:article).permit(:title, :body, :status)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "cobalt", password: "cobalt", only: :destroy

  def show
    @article = Article.find(params[:article_id])
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article)
      if @comment.commenter.length < 1
        flash[:commentNameError] = "Your Name has to be at least 1 character long."
      end
      if @comment.body.length < 1
        flash[:commentBodyError] = "Your Comment has to be at least 1 character long."
      end
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/about/contact.html.erb
<header class="contact-header">
  <a href="https://github.com/NorthOC" target='_blank' class='contact-link'>
      <%= image_tag('github-logo.png', width: '50%', class: 'contact-image', alt: "Github logo outline") %>
  </a>
</header>

app/views/about/index.html.erb
<header class='article-header'>
  <h1 class='article-title'>In One Sentence...</h1>
</header>

<div class="article-container">
    <p class='accent text-align-center'>A collection of various drug trip stories from around the world...</p>
</div>

<header class='article-header'>
  <h2 class='article-subtitle'>Mission statement</h2>
</header>

<div class="article-container">
    <p class='accent-lite text-align-center'>To educate the public on safe drug use and document various substance & dosage effects.</p>
</div>

<header class='article-header'>
  <h2 class='article-subtitle'>The Details</h2>
</header>

<div class="article-container">
    <section class="article-section text-align-justify">
      <p>Hi! I'm a non-profit one-man-army operation in the works. I started this website as a mere way of learning Ruby On Rails and, with time, it has evolved into something more. The plan is to launch this as a MVP, and build it from there. It might take some time, but, eventually we'll get there!</p>
      <p>For now, only I can add stories, but, in the future, you'll be able to do that too! The current version that you are seeing is made for TheOdinProject and will not be updated further.</p>
    </section>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |form|%>
  <div class='article-container'>
    <%= form.text_field :title, placeholder: 'Title', maxlength: '50'%>

    <% article.errors.full_messages_for(:title).each do |message|%>
      <div class='error-msg'><%= message %></div>
    <% end %>

  </div>

  <div class='article-container'>
    <%= form.text_area :body, placeholder: 'Body'%>
    
    <% article.errors.full_messages_for(:body).each do |message|%>
      <div class='error-msg'><%= message %></div>
    <% end %>

  </div>

  <div class="flex">
    <div class='article-flex-container'>
      <%= form.label :status, class: 'create-article' %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>
    <div class='article-flex-container text-align-right'>
      <%= form.submit 'Publish', class: 'button'%>
    </div>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1 class='article-title text-align-center'>Edit article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<header>
<h1 class='intro-title'>Trip Hub</h1>
</header>

<div class='container'>
<div class='flex list'>
  <% @articles.each do |article| %>
        <%= link_to(article, class: 'card weed') do%>
        <h5><%=article.title%></h5>
        <div class='card-desc'>
        <i class='float-left'><%= article.created_at.strftime("%Y-%m-%d %H:%M")%>
        <% if article.created_at != article.updated_at%>
        <%= '*'%>
        <%end%></i>
        <i><%= article.comments.public_count %> Comments </i>
        </div>
    <% end %>
  <% end %>

</div>
</div>

app/views/articles/new.html.erb
<h1 class='article-title text-align-center'>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<header class="article-header">
  <h1 class='article-title'><%= @article.title %></h1>
</header>

<div class="article-container">
  <section class="article-section text-align-justify">
  <% text = @article.body.split(/[\r\n\r\n]+/) %>
  <% text.each do |par|%>
  <p><%= par %></p>
  <% end %>
  </section>
  
  <div class='text-align-right end-line'>
    <%= link_to "Edit",edit_article_path(@article),class: 'edit-destroy'%><%= link_to "Delete",article_path(@article), class: 'edit-destroy', method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>

  <div class='comment-section'>
  <%= render @article.comments %>
  </div>
  <h2 class="article-subtitle add-comment">Add a comment:</h2>
  
  <%= render 'comments/form' %>
</div>

app/views/comments/_comment.html.erb
<% if !comment.commenter.nil? %>
  <div class="comment">
  
    <div class="flex-row">
      <p class='commenter'>
        <%= comment.commenter %>
      </p>
      <%= link_to '●', [comment.article, comment], class: 'comment-delete', method: :delete, data: {confirm: "Are you sure?" } %>
    </div>

    <p class='comment-body'>
      <%= comment.body %>
    </p>
    <p class='comment-time'><%= comment.created_at.strftime("%H:%M | %Y-%m-%d")%></p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.text_field :commenter, placeholder: 'Name' , class: 'field', maxlength: '25'%>
  </p>
  <p>
    <%= form.text_area :body, placeholder: 'Comment', class: 'field comment-text', maxlength: '3000'%>
  </p>
  <% if flash.any? %>
  <% flash.each do |type, msg| %>
  <div class='error-msg'>
  <%= msg %>
  </div>
  <% end %>
  <% end %>
  <p>
    <%= form.submit class: 'button'%>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trip Hub | Tales of drug trips and more!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='footer-cont'>
  <nav>
  <%= link_to "Contact", contact_path, class: 'navlink'%>
  <%= link_to "About", about_path, class: 'navlink'%>
  <a href='/' class='navlink'>Home</a>
  <%= link_to "+", new_article_path, class: 'new-article-nav'%>
  </nav>
    <%= yield %>
  <footer>Copyright 2022 @ NorthOC</footer>
  </div>
  </body>
</html>